// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkNOvi5HKeHrbGYwn5Ka-13QnYLdL1Baw',
    appId: '1:691961481743:web:fde8f8824bdb0b0488f17a',
    messagingSenderId: '691961481743',
    projectId: 'enactus-536af',
    authDomain: 'enactus-536af.firebaseapp.com',
    storageBucket: 'enactus-536af.firebasestorage.app',
    measurementId: 'G-0F132HQJ0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANaOqZzO82ZwBxgKcUZhPCOJZMTKRLVKY',
    appId: '1:691961481743:android:05a7811f283a87c488f17a',
    messagingSenderId: '691961481743',
    projectId: 'enactus-536af',
    storageBucket: 'enactus-536af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmPZVbemGtZ3hcnOMOKGiI0OWQE2GLK8',
    appId: '1:691961481743:ios:0ebd8e88587b9bff88f17a',
    messagingSenderId: '691961481743',
    projectId: 'enactus-536af',
    storageBucket: 'enactus-536af.firebasestorage.app',
    iosBundleId: 'com.example.session1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmPZVbemGtZ3hcnOMOKGiI0OWQE2GLK8',
    appId: '1:691961481743:ios:0ebd8e88587b9bff88f17a',
    messagingSenderId: '691961481743',
    projectId: 'enactus-536af',
    storageBucket: 'enactus-536af.firebasestorage.app',
    iosBundleId: 'com.example.session1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkNOvi5HKeHrbGYwn5Ka-13QnYLdL1Baw',
    appId: '1:691961481743:web:9179a09d30704ccf88f17a',
    messagingSenderId: '691961481743',
    projectId: 'enactus-536af',
    authDomain: 'enactus-536af.firebaseapp.com',
    storageBucket: 'enactus-536af.firebasestorage.app',
    measurementId: 'G-9WV25FN1EH',
  );
}
